import type {
  Difficulty,
  EvidenceLevel,
  Exercise,
  MuscleId,
  MuscleLoad,
  StudySource,
} from "@shared/types";

/**
 * Каталог упражнений. Цифры взяты из ЭМГ-исследований, а не придуманы.
 * Ссылки на первоисточники — в README проекта, в интерфейсе только подпись.
 *
 * Оговорка, которую нельзя терять: ЭМГ измеряет активацию в моменте,
 * а не прирост мышцы. Это помощь в выборе упражнения, не прогноз роста.
 */

export const sources: Record<string, StudySource> = {
  "ace-chest": {
    id: "ace-chest",
    label: "ACE · ЭМГ, грудь",
    note: "ACE / Univ. of Wisconsin–La Crosse, 2012. % от жима штанги лёжа",
  },
  "ace-triceps": {
    id: "ace-triceps",
    label: "ACE · ЭМГ, трицепс",
    note: "ACE, 2011. % от алмазных отжиманий",
  },
  "ace-biceps": {
    id: "ace-biceps",
    label: "ACE · рейтинг, бицепс",
    note: "ACE, 2014. Опубликован порядок, без процентов",
  },
  "ace-delts": {
    id: "ace-delts",
    label: "ACE · рейтинг, плечи",
    note: "ACE, 2014. Опубликованы лидеры по пучкам, без процентов",
  },
  "ace-abs": {
    id: "ace-abs",
    label: "ACE · рейтинг, пресс",
    note: "ACE / San Diego State Univ., 2001. Порядок из 13 упражнений",
  },
  estimate: {
    id: "estimate",
    label: "Оценка",
    note: "Сравнительного ЭМГ-исследования не нашли, значение экспертное",
  },
};

export const muscleNames: Record<MuscleId, string> = {
  traps: "Трапеции",
  delts: "Плечи",
  chest: "Грудь",
  biceps: "Бицепс",
  triceps: "Трицепс",
  forearms: "Предплечья",
  abs: "Пресс",
  obliques: "Косые",
  quads: "Квадрицепс",
  calves: "Икры",
};

export const difficultyLabels: Record<Difficulty, string> = {
  low: "Низкая",
  medium: "Средняя",
  high: "Высокая",
};

export const evidenceLabels: Record<EvidenceLevel, string> = {
  emg: "ЭМГ",
  ranking: "Рейтинг",
  estimate: "Оценка",
};

export const equipmentLabels = {
  barbell: "Штанга",
  dumbbell: "Гантели",
  machine: "Тренажёр",
  bodyweight: "Свой вес",
  cable: "Блок",
} as const;

/** Недельный объём: сделано подходов из целевого по росту/весу/возрасту */
export const initialLoads: MuscleLoad[] = [
  { muscleId: "chest", setsDone: 12, setsTarget: 14, ratio: 12 / 14 },
  { muscleId: "delts", setsDone: 9, setsTarget: 16, ratio: 9 / 16 },
  { muscleId: "biceps", setsDone: 8, setsTarget: 12, ratio: 8 / 12 },
  { muscleId: "triceps", setsDone: 5, setsTarget: 12, ratio: 5 / 12 },
  { muscleId: "traps", setsDone: 4, setsTarget: 8, ratio: 4 / 8 },
  { muscleId: "forearms", setsDone: 3, setsTarget: 8, ratio: 3 / 8 },
  { muscleId: "abs", setsDone: 6, setsTarget: 12, ratio: 6 / 12 },
  { muscleId: "obliques", setsDone: 2, setsTarget: 8, ratio: 2 / 8 },
  { muscleId: "quads", setsDone: 18, setsTarget: 16, ratio: 18 / 16 },
  { muscleId: "calves", setsDone: 2, setsTarget: 10, ratio: 2 / 10 },
];

export const demoExercises: Exercise[] = [
  // ── Грудь: ACE 2012, проценты от жима штанги лёжа ──────────────────────
  {
    id: "bb-bench",
    name: "Жим штанги лёжа",
    primary: "chest",
    secondary: ["triceps", "delts"],
    emgPercent: 100,
    evidence: "emg",
    sourceId: "ace-chest",
    difficulty: "medium",
    equipment: "barbell",
    note: "Эталон исследования — с ним сравнивали остальные",
  },
  {
    id: "pec-deck",
    name: "Пек-дек (бабочка)",
    primary: "chest",
    secondary: [],
    emgPercent: 98,
    evidence: "emg",
    sourceId: "ace-chest",
    difficulty: "low",
    equipment: "machine",
    note: "Плечо в уязвимом положении — осторожно, если оно беспокоит",
  },
  {
    id: "cable-crossover",
    name: "Кроссовер в наклоне вперёд",
    primary: "chest",
    secondary: [],
    emgPercent: 93,
    evidence: "emg",
    sourceId: "ace-chest",
    difficulty: "low",
    equipment: "cable",
    note: "По активации сопоставим с жимом — можно менять между собой",
  },
  {
    id: "machine-press",
    name: "Жим в тренажёре",
    primary: "chest",
    secondary: ["triceps"],
    emgPercent: 79,
    evidence: "emg",
    sourceId: "ace-chest",
    difficulty: "low",
    equipment: "machine",
  },
  {
    id: "incline-db-fly",
    name: "Разведения на наклонной",
    primary: "chest",
    secondary: [],
    emgPercent: 69,
    evidence: "emg",
    sourceId: "ace-chest",
    difficulty: "medium",
    equipment: "dumbbell",
  },
  {
    id: "dips-chest",
    name: "Отжимания на брусьях",
    primary: "chest",
    secondary: ["triceps", "delts"],
    emgPercent: 69,
    evidence: "emg",
    sourceId: "ace-chest",
    difficulty: "high",
    equipment: "bodyweight",
  },
  {
    id: "push-up",
    name: "Отжимания от пола",
    primary: "chest",
    secondary: ["triceps"],
    emgPercent: 61,
    evidence: "emg",
    sourceId: "ace-chest",
    difficulty: "low",
    equipment: "bodyweight",
  },

  // ── Трицепс: ACE 2011, проценты от алмазных отжиманий ──────────────────
  {
    id: "triangle-push-up",
    name: "Алмазные отжимания",
    primary: "triceps",
    secondary: ["chest"],
    emgPercent: 100,
    evidence: "emg",
    sourceId: "ace-triceps",
    difficulty: "medium",
    equipment: "bodyweight",
    note: "Лидер исследования, при этом не нужно оборудование",
  },
  {
    id: "triceps-kickback",
    name: "Разгибания в наклоне",
    primary: "triceps",
    secondary: [],
    emgPercent: 87,
    evidence: "emg",
    sourceId: "ace-triceps",
    difficulty: "low",
    equipment: "dumbbell",
  },
  {
    id: "dips-triceps",
    name: "Отжимания на брусьях узко",
    primary: "triceps",
    secondary: ["chest"],
    emgPercent: 87,
    evidence: "emg",
    sourceId: "ace-triceps",
    difficulty: "high",
    equipment: "bodyweight",
  },
  {
    id: "overhead-extension",
    name: "Разгибания из-за головы",
    primary: "triceps",
    secondary: [],
    emgPercent: 76,
    evidence: "emg",
    sourceId: "ace-triceps",
    difficulty: "medium",
    equipment: "dumbbell",
  },
  {
    id: "rope-pushdown",
    name: "Разгибания на блоке с канатом",
    primary: "triceps",
    secondary: [],
    emgPercent: 74,
    evidence: "emg",
    sourceId: "ace-triceps",
    difficulty: "low",
    equipment: "cable",
  },
  {
    id: "bar-pushdown",
    name: "Разгибания на блоке с рукоятью",
    primary: "triceps",
    secondary: [],
    emgPercent: 67,
    evidence: "emg",
    sourceId: "ace-triceps",
    difficulty: "low",
    equipment: "cable",
  },
  {
    id: "skullcrusher",
    name: "Французский жим лёжа",
    primary: "triceps",
    secondary: [],
    emgPercent: 62,
    evidence: "emg",
    sourceId: "ace-triceps",
    difficulty: "medium",
    equipment: "barbell",
  },
  {
    id: "close-grip-bench",
    name: "Жим узким хватом",
    primary: "triceps",
    secondary: ["chest", "delts"],
    emgPercent: 62,
    evidence: "emg",
    sourceId: "ace-triceps",
    difficulty: "medium",
    equipment: "barbell",
    note: "В исследовании ниже отжиманий: в свободных весах включается инерция",
  },

  // ── Бицепс: ACE 2014, только порядок ───────────────────────────────────
  {
    id: "concentration-curl",
    name: "Концентрированные сгибания",
    primary: "biceps",
    secondary: [],
    emgPercent: null,
    rank: 1,
    evidence: "ranking",
    sourceId: "ace-biceps",
    difficulty: "low",
    equipment: "dumbbell",
    note: "Локоть зафиксирован — корпус не помогает, работает только бицепс",
  },
  {
    id: "bb-curl",
    name: "Подъём штанги на бицепс",
    primary: "biceps",
    secondary: ["forearms"],
    emgPercent: null,
    rank: 2,
    evidence: "ranking",
    sourceId: "ace-biceps",
    difficulty: "low",
    equipment: "barbell",
  },
  {
    id: "cable-curl",
    name: "Сгибания на блоке",
    primary: "biceps",
    secondary: ["forearms"],
    emgPercent: null,
    rank: 3,
    evidence: "ranking",
    sourceId: "ace-biceps",
    difficulty: "low",
    equipment: "cable",
  },
  {
    id: "chin-up",
    name: "Подтягивания обратным хватом",
    primary: "biceps",
    secondary: ["forearms"],
    emgPercent: null,
    rank: 4,
    evidence: "ranking",
    sourceId: "ace-biceps",
    difficulty: "medium",
    equipment: "bodyweight",
  },
  {
    id: "ez-curl-narrow",
    name: "EZ-гриф узким хватом",
    primary: "biceps",
    secondary: ["forearms"],
    emgPercent: null,
    rank: 5,
    evidence: "ranking",
    sourceId: "ace-biceps",
    difficulty: "low",
    equipment: "barbell",
  },
  {
    id: "incline-curl",
    name: "Сгибания на наклонной",
    primary: "biceps",
    secondary: [],
    emgPercent: null,
    rank: 7,
    evidence: "ranking",
    sourceId: "ace-biceps",
    difficulty: "low",
    equipment: "dumbbell",
  },
  {
    id: "preacher-curl",
    name: "Скамья Скотта",
    primary: "biceps",
    secondary: [],
    emgPercent: null,
    rank: 8,
    evidence: "ranking",
    sourceId: "ace-biceps",
    difficulty: "low",
    equipment: "dumbbell",
  },

  // ── Плечи: ACE 2014, только лидеры по пучкам ───────────────────────────
  {
    id: "db-shoulder-press",
    name: "Жим гантелей сидя",
    primary: "delts",
    secondary: ["triceps", "traps"],
    emgPercent: null,
    rank: 1,
    evidence: "ranking",
    sourceId: "ace-delts",
    difficulty: "medium",
    equipment: "dumbbell",
    note: "Лидер по переднему пучку",
  },
  {
    id: "incline-row-45",
    name: "Тяга на наклонной 45°",
    primary: "delts",
    secondary: ["traps", "biceps"],
    emgPercent: null,
    rank: 2,
    evidence: "ranking",
    sourceId: "ace-delts",
    difficulty: "medium",
    equipment: "dumbbell",
    note: "Единственное в топе и по среднему, и по заднему пучку",
  },
  {
    id: "bent-arm-lateral",
    name: "Махи в стороны с согнутой рукой",
    primary: "delts",
    secondary: [],
    emgPercent: null,
    rank: 3,
    evidence: "ranking",
    sourceId: "ace-delts",
    difficulty: "low",
    equipment: "dumbbell",
    note: "Лидер по среднему пучку — он даёт ширину плеч",
  },
  {
    id: "seated-rear-lateral",
    name: "Махи в наклоне сидя",
    primary: "delts",
    secondary: ["traps"],
    emgPercent: null,
    rank: 4,
    evidence: "ranking",
    sourceId: "ace-delts",
    difficulty: "low",
    equipment: "dumbbell",
    note: "Лидер по заднему пучку",
  },
  {
    id: "db-front-raise",
    name: "Подъёмы перед собой",
    primary: "delts",
    secondary: [],
    emgPercent: null,
    rank: 6,
    evidence: "ranking",
    sourceId: "ace-delts",
    difficulty: "low",
    equipment: "dumbbell",
  },

  // ── Пресс: ACE 2001, порядок из 13 упражнений ──────────────────────────
  {
    id: "bicycle-crunch",
    name: "Велосипед",
    primary: "abs",
    secondary: ["obliques"],
    emgPercent: null,
    rank: 1,
    evidence: "ranking",
    sourceId: "ace-abs",
    difficulty: "low",
    equipment: "bodyweight",
    note: "Первое место и по прямой мышце, и по косым",
  },
  {
    id: "captains-chair",
    name: "Подъём ног в упоре",
    primary: "abs",
    secondary: ["obliques"],
    emgPercent: null,
    rank: 2,
    evidence: "ranking",
    sourceId: "ace-abs",
    difficulty: "medium",
    equipment: "bodyweight",
  },
  {
    id: "ball-crunch",
    name: "Скручивания на фитболе",
    primary: "abs",
    secondary: [],
    emgPercent: null,
    rank: 3,
    evidence: "ranking",
    sourceId: "ace-abs",
    difficulty: "low",
    equipment: "bodyweight",
  },
  {
    id: "vertical-leg-crunch",
    name: "Скручивания с поднятыми ногами",
    primary: "abs",
    secondary: [],
    emgPercent: null,
    rank: 4,
    evidence: "ranking",
    sourceId: "ace-abs",
    difficulty: "low",
    equipment: "bodyweight",
  },
  {
    id: "reverse-crunch",
    name: "Обратные скручивания",
    primary: "abs",
    secondary: ["obliques"],
    emgPercent: null,
    rank: 7,
    evidence: "ranking",
    sourceId: "ace-abs",
    difficulty: "low",
    equipment: "bodyweight",
  },
  {
    id: "plank-weighted",
    name: "Планка",
    primary: "abs",
    secondary: ["obliques"],
    emgPercent: null,
    rank: 10,
    evidence: "ranking",
    sourceId: "ace-abs",
    difficulty: "low",
    equipment: "bodyweight",
    note: "В рейтинге ниже скручиваний — держит корпус, но мало нагружает",
  },
  {
    id: "crunch",
    name: "Обычные скручивания",
    primary: "abs",
    secondary: [],
    emgPercent: null,
    rank: 11,
    evidence: "ranking",
    sourceId: "ace-abs",
    difficulty: "low",
    equipment: "bodyweight",
  },

  // ── Ниже — без сравнительного ЭМГ-исследования ─────────────────────────
  {
    id: "cable-woodchop",
    name: "Дровосек на блоке",
    primary: "obliques",
    secondary: ["abs"],
    emgPercent: 84,
    evidence: "estimate",
    sourceId: "estimate",
    difficulty: "medium",
    equipment: "cable",
  },
  {
    id: "side-plank",
    name: "Боковая планка",
    primary: "obliques",
    secondary: ["abs"],
    emgPercent: 78,
    evidence: "estimate",
    sourceId: "estimate",
    difficulty: "medium",
    equipment: "bodyweight",
  },
  {
    id: "db-side-bend",
    name: "Наклоны с гантелей",
    primary: "obliques",
    secondary: [],
    emgPercent: 70,
    evidence: "estimate",
    sourceId: "estimate",
    difficulty: "low",
    equipment: "dumbbell",
  },
  {
    id: "back-squat",
    name: "Приседания со штангой",
    primary: "quads",
    secondary: ["abs", "calves"],
    emgPercent: 95,
    evidence: "estimate",
    sourceId: "estimate",
    difficulty: "high",
    equipment: "barbell",
    note: "По активации квадрицепса сопоставим с жимом ногами, но нагружает спину",
  },
  {
    id: "leg-press",
    name: "Жим ногами",
    primary: "quads",
    secondary: ["calves"],
    emgPercent: 93,
    evidence: "estimate",
    sourceId: "estimate",
    difficulty: "low",
    equipment: "machine",
    note: "Разница с приседом не в активации мышцы, а в нагрузке на суставы",
  },
  {
    id: "smith-squat",
    name: "Приседания в Смите",
    primary: "quads",
    secondary: [],
    emgPercent: 82,
    evidence: "estimate",
    sourceId: "estimate",
    difficulty: "medium",
    equipment: "machine",
  },
  {
    id: "db-lunge",
    name: "Выпады с гантелями",
    primary: "quads",
    secondary: ["calves", "abs"],
    emgPercent: 78,
    evidence: "estimate",
    sourceId: "estimate",
    difficulty: "medium",
    equipment: "dumbbell",
  },
  {
    id: "leg-extension",
    name: "Разгибания ног",
    primary: "quads",
    secondary: [],
    emgPercent: 74,
    evidence: "estimate",
    sourceId: "estimate",
    difficulty: "low",
    equipment: "machine",
  },
  {
    id: "standing-calf-raise",
    name: "Подъёмы на носки стоя",
    primary: "calves",
    secondary: [],
    emgPercent: 90,
    evidence: "estimate",
    sourceId: "estimate",
    difficulty: "low",
    equipment: "machine",
  },
  {
    id: "leg-press-calf",
    name: "Носки в жиме ногами",
    primary: "calves",
    secondary: [],
    emgPercent: 84,
    evidence: "estimate",
    sourceId: "estimate",
    difficulty: "low",
    equipment: "machine",
  },
  {
    id: "seated-calf-raise",
    name: "Подъёмы на носки сидя",
    primary: "calves",
    secondary: [],
    emgPercent: 78,
    evidence: "estimate",
    sourceId: "estimate",
    difficulty: "low",
    equipment: "machine",
    note: "Камбаловидная — работает при согнутом колене",
  },
  {
    id: "db-shrug",
    name: "Шраги с гантелями",
    primary: "traps",
    secondary: ["forearms"],
    emgPercent: 88,
    evidence: "estimate",
    sourceId: "estimate",
    difficulty: "low",
    equipment: "dumbbell",
  },
  {
    id: "bb-shrug",
    name: "Шраги со штангой",
    primary: "traps",
    secondary: ["forearms"],
    emgPercent: 85,
    evidence: "estimate",
    sourceId: "estimate",
    difficulty: "low",
    equipment: "barbell",
  },
  {
    id: "upright-row",
    name: "Тяга к подбородку",
    primary: "traps",
    secondary: ["delts"],
    emgPercent: 70,
    evidence: "estimate",
    sourceId: "estimate",
    difficulty: "medium",
    equipment: "barbell",
  },
  {
    id: "farmers-walk",
    name: "Фермерская прогулка",
    primary: "forearms",
    secondary: ["traps", "abs"],
    emgPercent: 86,
    evidence: "estimate",
    sourceId: "estimate",
    difficulty: "low",
    equipment: "dumbbell",
  },
  {
    id: "wrist-curl",
    name: "Сгибания в запястьях",
    primary: "forearms",
    secondary: [],
    emgPercent: 82,
    evidence: "estimate",
    sourceId: "estimate",
    difficulty: "low",
    equipment: "barbell",
  },
  {
    id: "reverse-curl",
    name: "Обратные сгибания",
    primary: "forearms",
    secondary: ["biceps"],
    emgPercent: 74,
    evidence: "estimate",
    sourceId: "estimate",
    difficulty: "low",
    equipment: "barbell",
  },
];

/** Позиция в списке: сперва проценты, затем ранги. Чем меньше — тем выше. */
export function orderKey(e: Exercise): number {
  if (e.emgPercent !== null) return 100 - e.emgPercent;
  return 100 + (e.rank ?? 99);
}

/** Упражнения для мышцы — от самого доказанного и активного к остальным */
export function exercisesFor(muscleId: MuscleId): Exercise[] {
  return demoExercises
    .filter((e) => e.primary === muscleId)
    .sort((a, b) => orderKey(a) - orderKey(b));
}

const byId = new Map(demoExercises.map((e) => [e.id, e]));

export function exerciseById(id: string): Exercise {
  const found = byId.get(id);
  if (!found) throw new Error(`Неизвестное упражнение: ${id}`);
  return found;
}

/** Подпись значения для карточки: «100 %», «№1» или «—» */
export function scoreLabel(e: Exercise): string {
  if (e.emgPercent !== null) return String(e.emgPercent);
  if (e.rank) return `№${e.rank}`;
  return "—";
}
